import type { TripDay } from '../types';

// Generated by npm run import:data from the local public source workbook.
// Do not edit by hand; update the local public source workbook instead.
export const totalCost = '59,270 RMB';

export const tripDays: TripDay[] = [
  {
    "date": "9/25",
    "area": "上海出发",
    "stay": "夜宿飞机",
    "summary": "国际航班出发，重点是文件、行李和离线资料最后检查。",
    "meal": "飞机餐",
    "cost": "27,782 RMB",
    "route": "Shanghai → Helsinki → Oslo",
    "galleryImages": [],
    "riskTags": [
      "长途飞行",
      "文件检查"
    ],
    "timeline": [
      {
        "time": "20:50-05:55+1",
        "place": "Shanghai Pudong T2 → Helsinki-Vantaa",
        "title": "上海出发，Finnair AY088",
        "transport": "国际航班",
        "note": "证件、签证、保险、酒店和租车材料放在随身包。",
        "required": true
      }
    ],
    "reminders": [
      "确认托运行李和随身液体限制。",
      "手机离线地图、保险单、酒店订单离线保存。"
    ],
    "links": [
      {
        "label": "上海到奥斯陆路线",
        "url": "https://www.google.com/maps/search/Shanghai+to+Oslo",
        "kind": "地图"
      }
    ]
  },
  {
    "date": "9/26",
    "area": "奥斯陆 Oslo",
    "stay": "Oslo / Scandic Grensen",
    "summary": "抵达后轻量 citywalk，重点是缓冲时差，不把第一天塞满。",
    "meal": "TGTG 盲盒",
    "cost": "1,640 RMB",
    "route": "Oslo Airport → Oslo city center",
    "heroImage": "./assets/trip/excel-image1.jpeg",
    "galleryImages": [
      "./assets/trip/excel-image1.jpeg",
      "./assets/trip/excel-image2.jpeg",
      "./assets/trip/excel-image3.jpeg",
      "./assets/trip/excel-image4.jpeg"
    ],
    "riskTags": [
      "入境取行李",
      "次日早班"
    ],
    "timeline": [
      {
        "time": "05:55-07:50",
        "place": "Helsinki-Vantaa → Oslo Airport",
        "title": "赫尔辛基转机，AY911 到奥斯陆",
        "transport": "飞机",
        "note": "同一国际行程内转机，按现场登机口和航空公司通知为准。",
        "required": true
      },
      {
        "time": "07:50-09:20",
        "place": "Oslo Airport",
        "title": "抵达、入境、取行李、寄存大件行李",
        "required": true
      },
      {
        "time": "09:20-10:10",
        "place": "机场 → 奥斯陆市区",
        "title": "机场快线 / 地铁进城",
        "transport": "Flytoget / 公共交通",
        "note": "Flytoget 标称约 19 分钟，实际按 40-50 分钟预留。"
      },
      {
        "time": "11:00-12:00",
        "place": "Oslo Opera House",
        "title": "歌剧院外观、屋顶步道、海边拍照",
        "required": true
      },
      {
        "time": "12:00-14:20",
        "place": "Karl Johans gate / The Royal Palace",
        "title": "主街步行、午餐、王宫外观"
      },
      {
        "time": "14:40-16:30",
        "place": "Aker Brygge",
        "title": "码头散步、海边休息"
      },
      {
        "time": "16:30 后",
        "place": "Scandic Grensen",
        "title": "入住、晚餐、休息",
        "note": "第二天 06:23 出发，今晚不要太晚睡。",
        "required": true
      }
    ],
    "reminders": [
      "第一天不赶景点，优先恢复体力。",
      "次日早班车，睡前整理好行李。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/Oslo+Airport/Scandic+Grensen/Oslo+Opera+House/Karl+Johans+gate/The+Royal+Palace/Aker+Brygge",
        "kind": "地图"
      },
      {
        "label": "Flytoget 机场快线",
        "url": "https://flytoget.no/en/",
        "kind": "交通"
      }
    ]
  },
  {
    "date": "9/27",
    "area": "挪威缩影 / Voss",
    "stay": "Voss / Scandic Voss",
    "summary": "Oslo 到 Flåm，再坐峡湾邮轮到 Gudvangen，最后巴士到 Voss。",
    "meal": "剩饭",
    "cost": "4,030 RMB",
    "route": "Oslo → Myrdal → Flåm → Gudvangen → Voss",
    "galleryImages": [],
    "riskTags": [
      "早班车",
      "多段换乘",
      "游船衔接"
    ],
    "timeline": [
      {
        "time": "05:20-06:05",
        "place": "Scandic Grensen → Oslo S",
        "title": "退房、前往火车站",
        "required": true
      },
      {
        "time": "06:23-14:01",
        "place": "Oslo → Myrdal → Flåm",
        "title": "火车 + Flåm Railway",
        "transport": "火车",
        "required": true
      },
      {
        "time": "14:01-15:00",
        "place": "Flåm",
        "title": "午餐、咖啡、码头拍照",
        "note": "只有约 1 小时，不追加额外活动。"
      },
      {
        "time": "15:00-17:00",
        "place": "Flåm → Gudvangen",
        "title": "Nærøyfjord 峡湾游船",
        "transport": "船",
        "required": true
      },
      {
        "time": "17:15-18:20",
        "place": "Gudvangen → Voss",
        "title": "巴士到 Voss",
        "transport": "巴士",
        "required": true
      },
      {
        "time": "18:20 后",
        "place": "Scandic Voss",
        "title": "到站、入住、吃饭休息"
      }
    ],
    "reminders": [
      "游船票据提前下载离线保存。",
      "Flåm 停留短，别加活动。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/Oslo+S/Myrdal/Fl%C3%A5m/Gudvangen/Voss",
        "kind": "地图"
      },
      {
        "label": "Norway’s Best Nærøyfjord Cruise",
        "url": "https://www.norwaysbest.com/en/flam/things-to-do/fjord-cruise-naeroyfjord",
        "kind": "交通"
      }
    ]
  },
  {
    "date": "9/28",
    "area": "Voss / Bergen",
    "stay": "Bergen / Citybox Danmarksplass",
    "summary": "上午 Voss 湖区和可选缆车，下午到卑尔根看布吕根、港口和弗洛伊恩山。",
    "meal": "TGTG 盲盒",
    "cost": "1,050 RMB",
    "route": "Voss → Bergen",
    "galleryImages": [],
    "riskTags": [
      "天气决策",
      "火车衔接"
    ],
    "timeline": [
      {
        "time": "08:30-09:40",
        "place": "Voss / Vangsvatnet",
        "title": "Voss 湖区散步"
      },
      {
        "time": "09:50-11:40",
        "place": "Voss Gondol / Hangurstoppen",
        "title": "缆车可选",
        "note": "天气好就上；天气差就多留给卑尔根。"
      },
      {
        "time": "13:00-14:30",
        "place": "Voss → Bergen",
        "title": "火车去卑尔根",
        "transport": "火车"
      },
      {
        "time": "15:50-17:10",
        "place": "Bryggen",
        "title": "布吕根老码头街区游览",
        "required": true
      },
      {
        "time": "18:00-20:00",
        "place": "Mount Fløyen",
        "title": "缆车上山、看城市景"
      },
      {
        "time": "20:00 后",
        "place": "Citybox Danmarksplass",
        "title": "入住、晚餐、整理行李",
        "required": true
      }
    ],
    "reminders": [
      "Voss 缆车是天气触发项，不为它影响卑尔根主线。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/Voss/Vangsvatnet/Voss+Gondol/Bergen/Bryggen/Mount+Fl%C3%B8yen",
        "kind": "地图"
      }
    ]
  },
  {
    "date": "9/29",
    "area": "卑尔根 / 冰岛",
    "stay": "Reykjavik / B47",
    "summary": "当天只处理飞行、入境、取车和补给，不安排景点。",
    "meal": "泡面",
    "cost": "2,414 RMB",
    "drive": "45min",
    "fuel": "落地补给即可",
    "route": "Bergen → Oslo → Keflavik → Reykjavik",
    "galleryImages": [],
    "riskTags": [
      "航班日",
      "取车",
      "补给",
      "租车衔接"
    ],
    "timeline": [
      {
        "time": "08:30-09:30",
        "place": "Citybox Danmarksplass",
        "title": "退房、早餐、整理行李"
      },
      {
        "time": "09:30-10:20",
        "place": "酒店 → Bergen Airport",
        "title": "去机场",
        "transport": "公共交通 / 打车"
      },
      {
        "time": "12:00-12:55",
        "place": "Bergen → Oslo",
        "title": "Norwegian DY617",
        "transport": "飞机",
        "required": true
      },
      {
        "time": "17:15-18:05",
        "place": "Oslo → Keflavik / KEF",
        "title": "SAS SK4785 Oslo → Keflavik",
        "transport": "飞机",
        "required": true
      },
      {
        "time": "18:00 后",
        "place": "Keflavik / KEF",
        "title": "入境、取行李、取租车",
        "required": true
      },
      {
        "time": "19:45-20:30",
        "place": "机场 / 雷市路上",
        "title": "简单补给：水、零食、早餐、加油确认"
      },
      {
        "time": "20:30-21:15",
        "place": "Reykjavik / B47",
        "title": "开到雷市 B47，入住休息"
      }
    ],
    "reminders": [
      "租车取车时确认保险、碎石险、还车油量和紧急电话。",
      "当天不加景点，给航班延误留空间。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/Keflav%C3%ADk+International+Airport/Reykjav%C3%ADk+B47",
        "kind": "地图"
      },
      {
        "label": "冰岛实时路况 umferdin.is",
        "url": "https://umferdin.is/en",
        "kind": "安全"
      },
      {
        "label": "Safetravel Iceland",
        "url": "https://safetravel.is/",
        "kind": "安全"
      }
    ]
  },
  {
    "date": "9/30",
    "area": "Reykjavik / Reykjanes Peninsula",
    "stay": "Reykjavik / B47",
    "summary": "10:00 出发走雷克雅内斯半岛，Fagradalsfjall / Stórhóll 徒步后串联 Seltún、Brimketill、Gunnuhver、Valahnúkamöl，傍晚回雷市轻逛。",
    "meal": "小猪商店 + 泡面 / 车上简餐",
    "cost": "2,000 RMB",
    "drive": "约2.5-3.5h + 徒步",
    "fuel": "出发前确认油量，半岛不临时找补给",
    "route": "Reykjavik → Fagradalsfjall / Stórhóll → Seltún → Brimketill → Gunnuhver → Valahnúkamöl → Reykjavik",
    "heroImage": "./assets/places/fagradalsfjall-storholl.jpg",
    "galleryImages": [
      "./assets/places/fagradalsfjall-storholl.jpg",
      "./assets/places/seltun-reykjanes.jpg",
      "./assets/places/brimketill.jpg",
      "./assets/places/gunnuhver.jpg",
      "./assets/places/valahnukamol-reykjanesviti.jpg"
    ],
    "riskTags": [
      "半岛徒步",
      "风大可删",
      "时间压缩"
    ],
    "timeline": [
      {
        "time": "10:00-10:50",
        "place": "Reykjavik / B47 → Fagradalsfjall",
        "title": "雷市出发，前往火山徒步区",
        "transport": "自驾",
        "note": "按截图主计划收口到 10:00 出发；出发前确认风、雨、油量和徒步装备。",
        "required": true
      },
      {
        "time": "10:50-11:10",
        "place": "Fagradalsfjall 停车场 P1/P2",
        "title": "停车、厕所、整理徒步装备",
        "note": "徒步前确认防风、防水、补水和离线地图。",
        "required": true
      },
      {
        "time": "11:10-13:30",
        "place": "Stórhóll View Point / Fagradalsfjall",
        "title": "Fagradalsfjall / Stórhóll 徒步往返",
        "transport": "徒步",
        "note": "按 2 小时以上预留，含拍照休息；风大或雨大则缩短或取消。",
        "required": true
      },
      {
        "time": "13:30-14:00",
        "place": "Fagradalsfjall 停车场",
        "title": "回车休整 + 简单午餐",
        "note": "换袜子、补水、吃能量棒或三明治，不专门找餐厅。"
      },
      {
        "time": "14:20-15:00",
        "place": "Seltún Geothermal Area",
        "title": "Seltún 地热区",
        "note": "彩色地热、蒸汽和硫磺地貌，轻松短停。",
        "required": true
      },
      {
        "time": "15:20-15:45",
        "place": "Brimketill",
        "title": "熔岩海池、黑色岩岸",
        "note": "看海浪冲黑色岩岸；风大时缩短停留。"
      },
      {
        "time": "16:05-16:35",
        "place": "Gunnuhver",
        "title": "Gunnuhver 大蒸汽地热点",
        "note": "蒸汽强、视觉冲击大，注意风向和步道边界。",
        "required": true
      },
      {
        "time": "16:40-17:20",
        "place": "Valahnúkamöl / Reykjanesviti",
        "title": "黑海岸、灯塔、海崖",
        "note": "世界尽头感强；风大时只短停拍照。"
      },
      {
        "time": "17:20-18:10",
        "place": "Reykjanes Peninsula → Reykjavik",
        "title": "开回雷市",
        "transport": "自驾",
        "note": "如果天气差或累了，直接回住宿。",
        "required": true
      },
      {
        "time": "18:10 以后",
        "place": "Reykjavik city center",
        "title": "雷市吃饭 + 轻逛",
        "note": "Laugavegur、彩虹街、教堂周边轻松走走。"
      }
    ],
    "reminders": [
      "雷克雅内斯半岛天气和风很影响体验，出发前看 Vedur、Safetravel 和路况。",
      "Fagradalsfjall / Stórhóll 徒步按天气缩短；风雨差时优先保留 Seltún、Gunnuhver 等短停点。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/B47%20Reykjavik/Fagradalsfjall%20Parking%20P1/Selt%C3%BAn/Brimketill/Gunnuhver/Valahn%C3%BAkam%C3%B6l/Reykjanesviti/B47%20Reykjavik",
        "kind": "地图"
      },
      {
        "label": "Visit Reykjanes",
        "url": "https://www.visitreykjanes.is/en",
        "kind": "介绍"
      }
    ]
  },
  {
    "date": "10/1",
    "area": "Sky Lagoon / Golden Circle / Hella",
    "stay": "Hella / Ugla Guesthouse",
    "summary": "上午 Sky Lagoon 温泉，下午压缩黄金圈：辛格维利尔、间歇泉、Brúarfoss 蓝色秘境瀑布、黄金瀑布，结束后前往 Hella 入住。",
    "meal": "温泉简餐 / 泡面",
    "cost": "1,063 RMB",
    "drive": "约4.5-5.5h",
    "fuel": "离开雷市前或返程经 Selfoss 视油量补给",
    "route": "Reykjavik → Sky Lagoon → Thingvellir → Geysir → Brúarfoss → Gullfoss → Hella",
    "heroImage": "./assets/places/sky-lagoon.jpg",
    "galleryImages": [
      "./assets/places/sky-lagoon.jpg",
      "./assets/places/thingvellir.jpg",
      "./assets/places/geysir.jpg",
      "./assets/places/bruarfoss.jpg",
      "./assets/places/gullfoss.jpg"
    ],
    "riskTags": [
      "温泉预约",
      "黄金圈压缩版",
      "Brúarfoss 时间控制"
    ],
    "timeline": [
      {
        "time": "08:00-08:40",
        "place": "B47 → Sky Lagoon",
        "title": "退房装车，开往 Sky Lagoon",
        "transport": "自驾",
        "note": "温泉用品和当天证件放在容易拿的位置。",
        "required": true
      },
      {
        "time": "09:15-09:50",
        "place": "Sky Lagoon",
        "title": "到场停车、换衣、准备",
        "note": "10:00 预约入场，留出停车和更衣缓冲。",
        "required": true
      },
      {
        "time": "10:00-12:00",
        "place": "Sky Lagoon",
        "title": "Sky Lagoon 温泉",
        "transport": "活动",
        "note": "上午完成温泉，下午转入压缩黄金圈。",
        "required": true
      },
      {
        "time": "12:00-12:30",
        "place": "Sky Lagoon",
        "title": "简单午餐 / 换衣",
        "note": "不要拖太晚，下午黄金圈节点较紧。"
      },
      {
        "time": "12:30-13:35",
        "place": "Sky Lagoon → Thingvellir",
        "title": "驾驶：Sky Lagoon → 辛格维利尔",
        "transport": "自驾",
        "note": "下午开始黄金圈，按路况控制节奏。",
        "required": true
      },
      {
        "time": "13:35-14:20",
        "place": "Thingvellir National Park",
        "title": "游览：裂谷、观景步道",
        "note": "压缩游览，重点看裂谷和主步道。",
        "required": true
      },
      {
        "time": "14:20-15:10",
        "place": "Thingvellir → Geysir",
        "title": "驾驶：辛格维利尔 → Geysir",
        "transport": "自驾",
        "note": "中途不加额外景点。",
        "required": true
      },
      {
        "time": "15:10-15:45",
        "place": "Geysir Geothermal Area",
        "title": "游览：Strokkur 喷发",
        "note": "看几轮喷发后收口。",
        "required": true
      },
      {
        "time": "15:45-16:25",
        "place": "Geysir → Brúarfoss",
        "title": "驾驶：Geysir → Brúarfoss",
        "transport": "自驾",
        "note": "Brúarfoss 只保留蓝色瀑布核心停留。"
      },
      {
        "time": "16:25-17:00",
        "place": "Brúarfoss",
        "title": "Brúarfoss 蓝色秘境瀑布",
        "note": "蓝色水流很有辨识度；时间紧则只做短停拍照。",
        "required": true
      },
      {
        "time": "17:00-17:35",
        "place": "Brúarfoss → Gullfoss",
        "title": "驾驶：Brúarfoss → Gullfoss",
        "transport": "自驾",
        "note": "进入黄金瀑布前留停车和步行时间。"
      },
      {
        "time": "17:35-18:15",
        "place": "Gullfoss Waterfall",
        "title": "游览：黄金瀑布观景台",
        "note": "风大水汽重，步道按天气选择。",
        "required": true
      },
      {
        "time": "18:15-19:35",
        "place": "Gullfoss → Hella / Ugla Guesthouse",
        "title": "驾驶：Gullfoss → Hella",
        "transport": "自驾",
        "note": "结束黄金圈，直接去 Hella 入住。",
        "required": true
      },
      {
        "time": "19:35 以后",
        "place": "Ugla Guesthouse",
        "title": "入住、晚餐、休息",
        "note": "整理第二天南岸早出发物品。",
        "required": true
      }
    ],
    "reminders": [
      "Sky Lagoon 上午完成；下午黄金圈为压缩版，不追加 Kerið。",
      "Brúarfoss 与 Gullfoss 都要控制停留，优先准时到 Hella 住宿。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/B47%20Reykjavik/Sky%20Lagoon/Thingvellir%20National%20Park/Geysir/Br%C3%BAarfoss/Gullfoss/Ugla%20Guesthouse%20Hella",
        "kind": "地图"
      },
      {
        "label": "Sky Lagoon 官方站",
        "url": "https://www.skylagoon.com/",
        "kind": "官方"
      },
      {
        "label": "Brúarfoss 介绍",
        "url": "https://guidetoiceland.is/travel-iceland/drive/bruarfoss",
        "kind": "介绍"
      }
    ]
  },
  {
    "date": "10/2",
    "area": "南岸 / Vik / Hali",
    "stay": "Hali / Skyrhúsið Guesthouse",
    "summary": "南岸经典瀑布和黑沙滩日：塞里雅兰瀑布、Gljúfrabúi、Skógafoss、Kvernufoss、Dyrhólaey、Reynisfjara，傍晚收口后前往 Hali 住宿。",
    "meal": "泡面 / Skógar 或 Vík 简餐",
    "cost": "1,030 RMB",
    "drive": "长距离日，含 Vik → Hali 夜间段",
    "fuel": "Hella 满油出发，Vik 再补给",
    "route": "Hella → Seljalandsfoss → Gljúfrabúi → Skógafoss → Kvernufoss → Dyrhólaey → Reynisfjara → Hali",
    "heroImage": "./assets/places/seljalandsfoss.jpg",
    "galleryImages": [
      "./assets/places/seljalandsfoss.jpg?./assets/places/gljufrabui.jpg?./assets/places/skogafoss.jpg?./assets/places/kvernufoss.jpg?./assets/places/dyrholaey.jpg?./assets/places/reynisfjara-black-sand-beach.jpg"
    ],
    "riskTags": [
      "疯狗浪",
      "长距离驾驶",
      "按时收口"
    ],
    "timeline": [
      {
        "time": "08:30-09:20",
        "place": "Hella / Ugla Guesthouse → Seljalandsfoss",
        "title": "退房装车，开往塞里雅兰瀑布",
        "transport": "自驾",
        "note": "出发前看天气和风速。",
        "required": true
      },
      {
        "time": "09:20-10:05",
        "place": "Seljalandsfoss",
        "title": "塞里雅兰瀑布 Seljalandsfoss",
        "note": "绕后步道防水防滑，水汽大时控制停留。",
        "required": true
      },
      {
        "time": "10:05-10:35",
        "place": "Gljúfrabúi",
        "title": "Gljúfrabúi 隐藏瀑布",
        "transport": "步行",
        "note": "峡谷隐藏瀑布，鞋和外层尽量防水。",
        "required": true
      },
      {
        "time": "10:35-11:25",
        "place": "Seljalandsfoss → Skógafoss",
        "title": "驾驶：前往 Skógafoss",
        "transport": "自驾",
        "note": "南岸经典公路，按天气控制速度。"
      },
      {
        "time": "11:25-12:15",
        "place": "Skógafoss",
        "title": "斯科加瀑布 Skógafoss",
        "note": "底部 + 爬顶两个体验，按体力选择。",
        "required": true
      },
      {
        "time": "12:15-12:30",
        "place": "Skógafoss → Kvernufoss",
        "title": "驾驶：前往 Kvernufoss 停车点",
        "transport": "自驾",
        "note": "距离很近，给停车和步行留余量。"
      },
      {
        "time": "12:30-13:20",
        "place": "Kvernufoss",
        "title": "克维努瀑布 Kvernufoss",
        "note": "轻徒步，瀑布后方很值得去；体力差则删。",
        "required": true
      },
      {
        "time": "13:20-14:10",
        "place": "Skógar / 车上",
        "title": "午餐 + 前往 Dyrhólaey",
        "transport": "自驾",
        "note": "Skógar 附近或车上解决，不为餐厅绕远。"
      },
      {
        "time": "14:10-15:00",
        "place": "Dyrhólaey",
        "title": "Dyrhólaey 灯塔、海蚀门、海岸线",
        "note": "看海蚀门、灯塔和黑沙滩远景。",
        "required": true
      },
      {
        "time": "15:15-16:30",
        "place": "Reynisfjara Black Sand Beach",
        "title": "Reynisfjara 黑沙滩",
        "note": "玄武岩柱、黑沙、海蚀柱；小心海浪，不背对海。",
        "required": true
      },
      {
        "time": "16:30-17:30",
        "place": "Vík",
        "title": "补给、厕所、晚餐准备、极光准备",
        "note": "按截图主计划 17:30 收口；只做必要补给。",
        "required": true
      },
      {
        "time": "17:30-20:15",
        "place": "Vík → Hali / Skyrhúsið Guesthouse",
        "title": "前往 Hali 住宿",
        "transport": "自驾",
        "note": "按路况和体力控制节奏，路上只做必要短停。",
        "required": true
      },
      {
        "time": "20:15 后",
        "place": "Skyrhúsið Guesthouse",
        "title": "入住、简单晚餐、整理冰川装备",
        "note": "整理 10/3 冰川活动装备。",
        "required": true
      }
    ],
    "reminders": [
      "黑沙滩不背对海浪，不靠近湿沙浪线。",
      "17:30 后以收口和住宿方向为主，不再临时加景点。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/Hella/Seljalandsfoss/Glj%C3%BAfrab%C3%BAi/Sk%C3%B3gafoss/Kvernufoss/Dyrh%C3%B3laey/Reynisfjara/V%C3%ADk/Skyrh%C3%BAsi%C3%B0+Guesthouse",
        "kind": "地图"
      },
      {
        "label": "冰岛实时路况 umferdin.is",
        "url": "https://umferdin.is/en",
        "kind": "安全"
      },
      {
        "label": "Safetravel Iceland",
        "url": "https://safetravel.is/",
        "kind": "安全"
      },
      {
        "label": "Vedur 天气预报",
        "url": "https://en.vedur.is/weather/forecasts/areas/",
        "kind": "天气"
      }
    ]
  },
  {
    "date": "10/3",
    "area": "冰川 / 冰河湖 / Höfn",
    "stay": "Höfn / Sauðanes Guesthouse",
    "summary": "上午 09:30 冰川活动集合，不是下午；下午冰河湖和钻石沙滩，体力差就删 Fjallsarlon。",
    "meal": "泡面",
    "cost": "4,813 RMB",
    "drive": "4-5h",
    "fuel": "Hali / Höfn 方向留意补给",
    "route": "Hali → Glacier Adventure → Jökulsárlón → Diamond Beach → Höfn",
    "heroImage": "./assets/trip/excel-image15.jpeg",
    "galleryImages": [
      "./assets/trip/excel-image15.jpeg",
      "./assets/trip/excel-image16.jpeg"
    ],
    "riskTags": [
      "09:30 集合",
      "冰川装备",
      "体力消耗大",
      "活动衔接"
    ],
    "timeline": [
      {
        "time": "07:30-08:30",
        "place": "Skyrhúsið Guesthouse",
        "title": "早餐、退房、换徒步衣物、装车",
        "required": true
      },
      {
        "time": "09:10-09:30",
        "place": "Glacier Adventure Base Camp Hali 781 IS",
        "title": "报到、装备、安全说明",
        "required": true
      },
      {
        "time": "09:30-15:30",
        "place": "Vatnajökull Glacier",
        "title": "Blue Ice Cave Adventure",
        "note": "按集合时间执行，提前 20 分钟到集合点。",
        "required": true
      },
      {
        "time": "15:45-16:25",
        "place": "Fjallsarlon",
        "title": "冰河湖补充点",
        "note": "体力差或天气差直接跳过。"
      },
      {
        "time": "16:40-17:40",
        "place": "Jökulsárlón Glacier Lagoon",
        "title": "冰河湖主景点",
        "required": true
      },
      {
        "time": "17:40-18:20",
        "place": "Diamond Beach",
        "title": "钻石沙滩"
      },
      {
        "time": "18:20-19:30",
        "place": "冰河湖 → Höfn",
        "title": "开往 Höfn，入住 Sauðanes",
        "required": true
      }
    ],
    "reminders": [
      "冰川活动按 09:30 集合，不要误排成下午。",
      "带防水外层、手套、水和能量补给。",
      "官网提醒冰岛驾驶不可预测，前一晚住 Hali 附近是正确策略。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/Skyrh%C3%BAsi%C3%B0+Guesthouse/Glacier+Adventure+Base+Camp/Fjalls%C3%A1rl%C3%B3n/J%C3%B6kuls%C3%A1rl%C3%B3n/Diamond+Beach/H%C3%B6fn",
        "kind": "地图"
      },
      {
        "label": "Glacier Adventure 官方站",
        "url": "https://glacieradventure.is/",
        "kind": "官方"
      },
      {
        "label": "Glacier Adventure Summer Tour",
        "url": "https://glacieradventure.is/tour/glacier-adventure-summer-tour/",
        "kind": "官方"
      },
      {
        "label": "冰岛实时路况 umferdin.is",
        "url": "https://umferdin.is/en",
        "kind": "安全"
      }
    ]
  },
  {
    "date": "10/4",
    "area": "Höfn → 机场附近",
    "stay": "机场附近 / Lighthouse-Inn",
    "summary": "全程最长驾驶日。核心是安全返程，天气差就取消补漏，直奔机场附近。",
    "meal": "泡面",
    "cost": "1,000 RMB",
    "drive": "6-7h",
    "fuel": "Vik / Hvolsvöllur",
    "route": "Höfn → Fjaðrárgljúfur → South Coast → Keflavik / Garður",
    "heroImage": "./assets/trip/excel-image17.jpeg",
    "galleryImages": [
      "./assets/trip/excel-image17.jpeg",
      "./assets/trip/excel-image18.jpeg",
      "./assets/trip/excel-image19.jpeg"
    ],
    "riskTags": [
      "最长驾驶日",
      "天气优先",
      "早班机前夜"
    ],
    "timeline": [
      {
        "time": "07:30-08:00",
        "place": "Sauðanes Guesthouse",
        "title": "退房、装车",
        "required": true
      },
      {
        "time": "08:00-11:30",
        "place": "Höfn → Fjaðrárgljúfur",
        "title": "长距离返程",
        "note": "中途只做厕所 / 咖啡短停。",
        "required": true
      },
      {
        "time": "11:30-12:30",
        "place": "Fjaðrárgljúfur Canyon",
        "title": "峡谷步道、观景台"
      },
      {
        "time": "13:15-15:20",
        "place": "往 Vik / Hvolsvöllur 方向返程",
        "title": "进入沿途补漏区间"
      },
      {
        "time": "15:20-16:20",
        "place": "南岸补漏点",
        "title": "Reynisfjara / Skogafoss / Kvernufoss / Vik 小镇只选一个",
        "note": "不能全补。天气差则取消。"
      },
      {
        "time": "16:20-19:30",
        "place": "南岸 → Keflavik / Garður",
        "title": "开往机场附近 Lighthouse-Inn",
        "required": true
      },
      {
        "time": "19:30 后",
        "place": "Lighthouse-Inn",
        "title": "入住、整理行李、确认还车流程",
        "note": "10/5 08:35 飞机，今晚确认油量和还车路线。"
      }
    ],
    "reminders": [
      "当天早上和中午都查 umferdin.is、Safetravel、Vedur。",
      "如果天气差，取消补漏直奔酒店。",
      "睡前确认加油、还车点和出发时间。"
    ],
    "links": [
      {
        "label": "当天地图",
        "url": "https://www.google.com/maps/dir/H%C3%B6fn/Fja%C3%B0r%C3%A1rglj%C3%BAfur/Keflav%C3%ADk+International+Airport/Lighthouse-Inn+Gar%C3%B0ur",
        "kind": "地图"
      },
      {
        "label": "冰岛实时路况 umferdin.is",
        "url": "https://umferdin.is/en",
        "kind": "安全"
      },
      {
        "label": "Safetravel Iceland",
        "url": "https://safetravel.is/",
        "kind": "安全"
      },
      {
        "label": "Vedur 天气预报",
        "url": "https://en.vedur.is/weather/forecasts/areas/",
        "kind": "天气"
      }
    ]
  },
  {
    "date": "10/5",
    "area": "返程 / Helsinki 转机",
    "stay": "返程",
    "summary": "早班机离开冰岛，赫尔辛基 10h 转机可做 citywalk，但至少提前 2.5-3h 回机场。",
    "meal": "外带早餐",
    "route": "Keflavik → Helsinki → citywalk → airport",
    "galleryImages": [],
    "riskTags": [
      "早班机",
      "还车",
      "转机缓冲"
    ],
    "timeline": [
      {
        "time": "05:30-05:45",
        "place": "Lighthouse-Inn",
        "title": "出发去机场还车点",
        "required": true
      },
      {
        "time": "05:45-06:20",
        "place": "Keflavik Airport / KEF",
        "title": "还车、接驳到航站楼",
        "required": true
      },
      {
        "time": "08:35-15:00",
        "place": "KEF → Helsinki / HEL",
        "title": "飞赫尔辛基",
        "transport": "飞机",
        "required": true
      },
      {
        "time": "抵达后约 1-1.5h",
        "place": "Helsinki Airport → City Centre",
        "title": "机场火车进市区",
        "transport": "火车"
      },
      {
        "time": "中转可用时间内",
        "place": "Helsinki citywalk",
        "title": "中央车站、大教堂、元老院广场、集市广场、Esplanadi"
      },
      {
        "time": "22:00-23:00",
        "place": "Helsinki city centre → Helsinki Airport",
        "title": "返回机场，准备深夜返程航班",
        "transport": "火车",
        "required": true
      }
    ],
    "reminders": [
      "至少提前 2.5-3 小时回到机场。",
      "如果入境、行李或天气不顺，直接留在机场。"
    ],
    "links": [
      {
        "label": "赫尔辛基 citywalk 地图",
        "url": "https://www.google.com/maps/dir/Helsinki+Central+Station/Helsinki+Cathedral/Senate+Square/Market+Square,+Helsinki/Esplanadi",
        "kind": "地图"
      },
      {
        "label": "HSL Helsinki Airport Train",
        "url": "https://www.hsl.fi/en/travelling/visitors/airport-train",
        "kind": "交通"
      }
    ]
  },
  {
    "date": "10/6",
    "area": "返抵上海",
    "stay": "回家",
    "summary": "深夜从赫尔辛基起飞，傍晚抵达上海浦东，旅行收尾日只保留回家交通和休息。",
    "meal": "飞机餐",
    "route": "Helsinki → Shanghai",
    "galleryImages": [],
    "riskTags": [
      "长途飞行",
      "落地恢复"
    ],
    "timeline": [
      {
        "time": "01:00-18:25",
        "place": "Helsinki-Vantaa → Shanghai Pudong T2",
        "title": "Finnair AY087 返程回上海",
        "transport": "国际航班",
        "required": true
      },
      {
        "time": "18:25 后",
        "place": "Shanghai Pudong T2",
        "title": "抵达上海、取行李、回家",
        "note": "落地后预留取行李、入境和回家交通时间。",
        "required": true
      }
    ],
    "reminders": [
      "长途飞行后不要安排高强度事项。",
      "回家后整理票据、照片和费用。"
    ],
    "links": [
      {
        "label": "上海浦东机场",
        "url": "https://www.shanghaiairport.com/index_enpdjc.html",
        "kind": "交通"
      },
      {
        "label": "机场到家路线",
        "url": "https://www.google.com/maps/search/Shanghai+Pudong+International+Airport",
        "kind": "地图"
      }
    ]
  }
];
